title: "Мой сайт на GitHub Pages"
description: "Простой статический сайт с блогом"
author: "Ваше Имя"
email: "your-email@example.com"
url: "https://test001.gv201-pages.dev.gitverse.sbt/default_jekyll"

# Настройки Jekyll
permalink: /:year/:month/:day/:title.html
timezone: Europe/Moscow

# Минимальная тема (встроенная в GitHub Pages)
theme: minima

# Плагины
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Настройки для сборки
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: assets/css

# Кастомные переменные
github_username: yourusername
twitter_username: yourtwitter
